# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 470)
        self.search = QtWidgets.QPushButton(Form)
        self.search.setGeometry(QtCore.QRect(10, 390, 271, 51))
        self.search.setObjectName("search")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 271, 16))
        self.label.setObjectName("label")
        self.lon = QtWidgets.QLineEdit(Form)
        self.lon.setGeometry(QtCore.QRect(10, 50, 271, 20))
        self.lon.setObjectName("lon")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 271, 16))
        self.label_2.setObjectName("label_2")
        self.lat = QtWidgets.QLineEdit(Form)
        self.lat.setGeometry(QtCore.QRect(10, 130, 271, 20))
        self.lat.setObjectName("lat")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 271, 16))
        self.label_3.setObjectName("label_3")
        self.scale = QtWidgets.QLineEdit(Form)
        self.scale.setGeometry(QtCore.QRect(10, 330, 271, 20))
        self.scale.setObjectName("scale")
        self.map = QtWidgets.QLabel(Form)
        self.map.setGeometry(QtCore.QRect(291, 10, 450, 450))
        self.map.setText("")
        self.map.setObjectName("map")
        self.map_showing = QtWidgets.QRadioButton(Form)
        self.map_showing.setGeometry(QtCore.QRect(10, 210, 91, 19))
        self.map_showing.setObjectName("map_showing")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.map_showing)
        self.sattelite_showing = QtWidgets.QRadioButton(Form)
        self.sattelite_showing.setGeometry(QtCore.QRect(100, 210, 91, 19))
        self.sattelite_showing.setObjectName("sattelite_showing")
        self.buttonGroup.addButton(self.sattelite_showing)
        self.gibrid_showing = QtWidgets.QRadioButton(Form)
        self.gibrid_showing.setGeometry(QtCore.QRect(210, 210, 91, 19))
        self.gibrid_showing.setObjectName("gibrid_showing")
        self.buttonGroup.addButton(self.gibrid_showing)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search.setText(_translate("Form", "Вывод"))
        self.label.setText(_translate("Form", "Ширина:"))
        self.label_2.setText(_translate("Form", "Долгота:"))
        self.label_3.setText(_translate("Form", "Масштабирование(0-17):"))
        self.map_showing.setText(_translate("Form", "Схема"))
        self.sattelite_showing.setText(_translate("Form", "Спутник"))
        self.gibrid_showing.setText(_translate("Form", "Гибрид"))
