# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 470)
        self.search = QtWidgets.QPushButton(Form)
        self.search.setGeometry(QtCore.QRect(10, 390, 271, 51))
        self.search.setObjectName("search")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 271, 16))
        self.label.setObjectName("label")
        self.lon = QtWidgets.QLineEdit(Form)
        self.lon.setGeometry(QtCore.QRect(10, 50, 271, 20))
        self.lon.setObjectName("lon")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 271, 16))
        self.label_2.setObjectName("label_2")
        self.lat = QtWidgets.QLineEdit(Form)
        self.lat.setGeometry(QtCore.QRect(10, 180, 271, 20))
        self.lat.setObjectName("lat")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 271, 16))
        self.label_3.setObjectName("label_3")
        self.scale = QtWidgets.QLineEdit(Form)
        self.scale.setGeometry(QtCore.QRect(10, 330, 271, 20))
        self.scale.setObjectName("scale")
        self.map = QtWidgets.QLabel(Form)
        self.map.setGeometry(QtCore.QRect(291, 10, 450, 450))
        self.map.setText("")
        self.map.setObjectName("map")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search.setText(_translate("Form", "Вывод"))
        self.label.setText(_translate("Form", "Широта:"))
        self.label_2.setText(_translate("Form", "Долгота:"))
        self.label_3.setText(_translate("Form", "Масштабирование(0-17):"))
